version: '3'

services:
  laravel:
    container_name: ${CONTAINER_APP_NAME}
    build: .
    volumes: 
      - .:/usr/src/${APP_NAME}
    command: |
      /bin/bash -c "
        composer install
        php artisan serve --host 0.0.0.0
        /bin/bash || exit 0 "
    ports:
      - "${APP_PORT}:8000"
    depends_on:
      - db

  db:
    container_name: ${CONTAINER_DB_NAME}
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${CONTAINER_DB_ADMINISTRATION}
    volumes:
      - /sessions
      - ./phpmyadmin.php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - ${DB_AD_PORT}:80
    environment:
      - PMA_HOST=db
      #- PMA_ARBITRARY=1
      #- TESTSUITE_PASSWORD=example
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db